[project]
name = "libro-sql"
version = "0.1.3"
description = "libro flow"
authors = [
    { name = "brokun", email = "brokun0128@gmail.com" },
    { name = "sunshinesmilelk", email = "1176136681@qq.com" },
]
dependencies = [
    "ipython>=7.34.0",
    "sqlalchemy>=2.0.34",
    "pandas>=2.2.2",
    "pydantic>=2.9.1",
    "psycopg2-binary>=2.9.9",
    "pymysql>=1.1.1",
]
dev-dependencies = []
readme = "README.md"
requires-python = ">= 3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/libro_sql"]
